---
apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  type: NodePort
  selector:
    app: catalog
  ports:
  - protocol: TCP
    port: 8020
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: catalog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: djcatalog
        image: 0.0.0.0:5000/catalog:latest
        ports:
        - containerPort: 8020
